ARG BASE_IMAGE=ghcr.io/aixcc-finals/base-runner:v1.3.0
FROM ${BASE_IMAGE}

RUN apt-get update && apt-get install -y software-properties-common
RUN apt-get update && apt-get install -y jq rsync openssh-client curl build-essential python3-dev
RUN pip3 install pyyaml requests pydantic rich

RUN mkdir -p /shellphish

RUN echo "kw1=\"FUZZ\"" > /shellphish/dict.txt

COPY shellphish-src/libs/crs-utils/src/shellphish_crs_utils/oss_fuzz/instrumentation/shellphish_libfuzzer/minimize_corpus_and_same_node_sync.sh /shellphish/minimize_corpus_and_same_node_sync.sh

# --- OSS-CRS glue ---
COPY --from=libcrs . /libCRS
RUN /libCRS/install.sh
COPY bin/run_libfuzzer.sh /usr/local/bin/run_libfuzzer.sh
RUN chmod +x /usr/local/bin/run_libfuzzer.sh
ENTRYPOINT ["/usr/local/bin/run_libfuzzer.sh"]
