[book]
authors = ["Andrew Chin", "Cen Zhang"]
language = "en"
src = "src"
title = "Artiphishell"

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output]

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
